# Generated by Django 3.2 on 2024-04-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardEpi',
        ),
        migrations.DeleteModel(
            name='Epi',
        ),
        migrations.AddField(
            model_name='board',
            name='construtora',
            field=models.CharField(default='Ativa', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativa', 'Inativa')], default='Ativa', max_length=20),
        ),
        migrations.AddField(
            model_name='board',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
