# Generated by Django 3.2 on 2024-04-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_board_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='construtora',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
