# Generated by Django 3.2 on 2024-12-30 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('construtora', models.CharField(blank=True, max_length=200, null=True)),
                ('board', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Ativa', 'Ativa'), ('Inativa', 'Inativa')], default='Ativa', max_length=20)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
