# Generated by Django 3.2 on 2024-12-30 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('card', models.CharField(max_length=200)),
                ('card2', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('macro', models.CharField(default=None, max_length=200, null=True)),
                ('cardUrl', models.CharField(max_length=200)),
                ('cardActive', models.CharField(max_length=200)),
                ('checklist', models.CharField(max_length=200)),
                ('pacote', models.CharField(max_length=200)),
                ('item1', models.CharField(max_length=200)),
                ('item2', models.CharField(max_length=200)),
                ('item3', models.CharField(max_length=200)),
                ('item4', models.CharField(max_length=200)),
                ('item5', models.CharField(max_length=200)),
                ('i1_status', models.CharField(max_length=200)),
                ('i2_status', models.CharField(max_length=200)),
                ('i3_status', models.CharField(max_length=200)),
                ('i4_status', models.CharField(max_length=200)),
                ('i5_status', models.CharField(max_length=200)),
                ('i1_user', models.CharField(max_length=200)),
                ('i2_user', models.CharField(max_length=200)),
                ('i3_user', models.CharField(max_length=200)),
                ('i4_user', models.CharField(max_length=200)),
                ('i5_user', models.CharField(max_length=200)),
                ('i1_date_auto', models.DateTimeField(blank=True, default=None, null=True)),
                ('i2_date_auto', models.DateTimeField(blank=True, default=None, null=True)),
                ('i3_date_auto', models.DateTimeField(blank=True, default=None, null=True)),
                ('i4_date_auto', models.DateTimeField(blank=True, default=None, null=True)),
                ('i5_date_auto', models.DateTimeField(blank=True, default=None, null=True)),
                ('i1_data', models.CharField(max_length=200)),
                ('i2_data', models.CharField(max_length=200)),
                ('i3_data', models.CharField(max_length=200)),
                ('med', models.CharField(max_length=200)),
                ('equipe', models.CharField(max_length=200)),
                ('hour', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('complete', models.IntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boards.board')),
            ],
        ),
    ]
